[package]
name = "limpid-core"
description = "Scanning and cleaning engine for Limpid"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
tracing.workspace = true

ignore = "0.4"
rayon = "1.11"
dirs = "7.0"
rustix = { version = "1.1", features = ["fs"] }
trash = "5.2"

[dev-dependencies]
tempfile = "3.24"
